theme: minima
title: How did you get in here?
author: Michael-Hart-Github
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the descirption of my blag. I put stuff here to let people know what it's about.

# social links
twitter_username: nope # DO NOT include the @ character, or else the build will fail!
github_username:  michael-hart-github # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
